import { describe, it, expect, vi } from 'vitest';

vi.mock('@/lib/db', () => ({ prisma: {} }));

import { calibratePriceElasticity, extractCalibrationDataPoints } from '@/lib/elasticity-calibration';

describe('calibratePriceElasticity', () => {
  it('returns null with fewer than 2 data points', () => {
    expect(calibratePriceElasticity([])).toBeNull();
    expect(calibratePriceElasticity([{ priceIncrease: 10, revenueMultiplier: 1.05 }])).toBeNull();
  });

  it('returns null when every run used the same price increase (no slope to fit)', () => {
    const points = [
      { priceIncrease: 10, revenueMultiplier: 1.05 },
      { priceIncrease: 10, revenueMultiplier: 1.03 },
    ];
    expect(calibratePriceElasticity(points)).toBeNull();
  });

  it('recovers a known elasticity from data generated by the engine\'s own linear model', () => {
    // revenueMultiplier - 1 ~= (p/100) * (1 - E). Pick E = 0.5 and generate
    // exact points from that formula — the fit should recover ~0.5.
    const E = 0.5;
    const points = [0, 10, 20, 30].map((p) => ({
      priceIncrease: p,
      revenueMultiplier: 1 + (p / 100) * (1 - E),
    }));

    const result = calibratePriceElasticity(points);

    expect(result).not.toBeNull();
    expect(result!.priceElasticityCoefficient).toBeCloseTo(E, 5);
    expect(result!.sampleSize).toBe(4);
  });

  it('clamps an implied elasticity below 0 (revenue outpacing price increases) to 0', () => {
    // revenueMultiplier rising faster than 1% per 1% price increase implies E < 0.
    const points = [
      { priceIncrease: 0, revenueMultiplier: 1.0 },
      { priceIncrease: 10, revenueMultiplier: 1.3 },
    ];
    const result = calibratePriceElasticity(points)!;
    expect(result.priceElasticityCoefficient).toBe(0);
  });

  it('clamps an implied elasticity above 2 (revenue collapsing on small price increases) to 2', () => {
    const points = [
      { priceIncrease: 0, revenueMultiplier: 1.0 },
      { priceIncrease: 10, revenueMultiplier: 0.5 },
    ];
    const result = calibratePriceElasticity(points)!;
    expect(result.priceElasticityCoefficient).toBe(2);
  });
});

describe('extractCalibrationDataPoints', () => {
  function makeScenario(overrides: Partial<Parameters<typeof extractCalibrationDataPoints>[0][number]> = {}) {
    return {
      priceIncrease: 10,
      priceElasticityOverride: null,
      simulationResults: [{ actualRevenue: 110000, monthlyDataJson: JSON.stringify([{ baselineRevenue: 100000 }]) }],
      ...overrides,
    };
  }

  it('computes revenueMultiplier from actualRevenue over the final period\'s baselineRevenue', () => {
    const points = extractCalibrationDataPoints([makeScenario()]);
    expect(points).toEqual([{ priceIncrease: 10, revenueMultiplier: 1.1 }]);
  });

  it('excludes scenarios with an explicit priceElasticityOverride — not a genuine market response', () => {
    const points = extractCalibrationDataPoints([makeScenario({ priceElasticityOverride: 0.7 })]);
    expect(points).toEqual([]);
  });

  it('excludes scenarios with no backfilled actual yet', () => {
    const points = extractCalibrationDataPoints([
      makeScenario({ simulationResults: [{ actualRevenue: null, monthlyDataJson: '[]' }] }),
    ]);
    expect(points).toEqual([]);
  });

  it('excludes scenarios with no simulation result at all', () => {
    const points = extractCalibrationDataPoints([makeScenario({ simulationResults: [] })]);
    expect(points).toEqual([]);
  });

  it('excludes scenarios with malformed monthlyDataJson instead of throwing', () => {
    const points = extractCalibrationDataPoints([
      makeScenario({ simulationResults: [{ actualRevenue: 110000, monthlyDataJson: 'not json' }] }),
    ]);
    expect(points).toEqual([]);
  });

  it('mixes valid and invalid scenarios, keeping only the valid ones', () => {
    const points = extractCalibrationDataPoints([
      makeScenario({ priceIncrease: 5 }),
      makeScenario({ priceIncrease: 15, priceElasticityOverride: 0.9 }),
      makeScenario({ priceIncrease: 20, simulationResults: [{ actualRevenue: null, monthlyDataJson: '[]' }] }),
    ]);
    expect(points).toEqual([{ priceIncrease: 5, revenueMultiplier: 1.1 }]);
  });
});
